package lt.vu.mif.MyBatis.Mappers;

import java.util.List;
import lt.vu.mif.MyBatis.ViewModels.ShopCar;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ShopCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS_CARS
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    int insert(ShopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS_CARS
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    List<ShopCar> selectAll();
}