package lt.vu.mif.MyBatis.ViewModels;

public class ShopCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS_CARS.SHOPS_ID
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    private Integer shopsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS_CARS.CARS_ID
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    private Integer carsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS_CARS.SHOPS_ID
     *
     * @return the value of PUBLIC.SHOPS_CARS.SHOPS_ID
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    public Integer getShopsId() {
        return shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS_CARS.SHOPS_ID
     *
     * @param shopsId the value for PUBLIC.SHOPS_CARS.SHOPS_ID
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    public void setShopsId(Integer shopsId) {
        this.shopsId = shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS_CARS.CARS_ID
     *
     * @return the value of PUBLIC.SHOPS_CARS.CARS_ID
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    public Integer getCarsId() {
        return carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS_CARS.CARS_ID
     *
     * @param carsId the value for PUBLIC.SHOPS_CARS.CARS_ID
     *
     * @mbg.generated Tue Apr 23 14:24:23 EEST 2019
     */
    public void setCarsId(Integer carsId) {
        this.carsId = carsId;
    }
}